// fitness-blog/app/layout.tsx
import { Inter } from "next/font/google";
import { Metadata } from "next";
import "./globals.css";
import Header from "./ui/components/Header";
import Footer from "./ui/components/Footer";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        <Header />
        {children}
        <Footer />
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
